dataset: dataset_female_4clotypes
name: CAPE_nz18_pose24_clotype8_female
lambda_latent: 0.0008
lambda_edge: 1.0
num_conv_layers: 8
nf: 64
nz: 18
nz_cond: 24
nz_cond2: 8
pose_type: rot
cond_encoder: 0
reduce_dim: 64
lr: 0.008
use_res_block: 0
use_res_block_dec: 1
affine: 0
num_epochs: 60
lr_warmup: 1
decay_every: 2
gender: female
mode: demo
vis_demo: 1